apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: search-engine
  description: search engine description search engine description search engine description
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: system-a
  dependsOn:
    - component:elastic-search
    - component:search-indexer
  hasPart:
    - component:search-adapter
    - component:search-indexer
    - component:elastic-search
  subcomponentOf:
    - component:search-indexer
  partOf:
    - component:search-indexer    
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: search-adapter
  description: search adapter
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: system-a
  dependsOn:
    - resource:xxx
  providesApis:
    - adapter-api-xxx
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: search-indexer
  description: search indexer
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: system-a
  dependsOn:
    - resource:default/search-adapter
    - component:default/search-adapter
    - service:default/search-adapter
    - component:search-adapter
  providesApis:
    - indexer-api-xxx
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elastic-search
  description: elastic search
spec:
  type: library
  lifecycle: production
  owner: team-a
  system: system-a
  dependsOn:
    - resource:search-indexer
